services:
  mysql:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  app:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    image: mysql-explain
    ports:
      - 3000:3000
    environment: 
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
      MYSQY_DATABASE: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: mysql
      EXPLAIN_RESULT_SLACK_CHANNEL_ID: ${EXPLAIN_RESULT_SLACK_CHANNEL_ID}